[package]
name = "mysql-udf-http-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
reqwest = { version = "0.12.4", features = ["blocking","__tls","gzip","charset"] ,default-features = true}
serde_json = "1.0.117"
udf = "0.5.5"

[lib]
crate-type = ["cdylib"]